- CoZ Application Form.md
> Create CoZ Application Form.md

- Community Workflow.md
Necessary change because of uncertainty.
> Update Community Workflow.md

- resources.md
A few missing links, like dBFT English version and NEO Chinese tutorial
> Updated Community Resources

- README.md
- The README was not in the correct "awesome" format.
- Missing details about SDKs.
> Add SDKs to README

- README.md
- Missing any information on wallets.
> Add Wallets to README

- README.md
Added the exchanges with description + content listing. Added a few exchanges as comments since they are not currently available for buying NEO, but will probably be once the Chinese situation is resolved.
<i>Exchanges are awesome because we need to be able to buy NEO! </i>
> Add exchanges to README

- README.md
Added Trello to README. It's awesome because it makes it more visible what everyone is working on.
> Add Trello to README

- README.md
Added private net tutorial since Afong and Ashant pointed out it should be easier to find. It's awesome because it skips having to create your own blockchain and gives you NEO and GAS w/o begging.
> Add private net tutorial

- README.md
I added a link to the NEOverse block explorer.  (Source can be found at https://github.com/neoverse/explorer, should add a link for that as well?)
> Added NEOverse block explorer link

- README.md
- resources/dapps.md
- resources/faq.md
Because it's an important part of the design of NEO.
> Add links, FAQ questions

- README.md
I found a new block explorer, and it isn't in the repo.
Add https://neoexplorer.co to list.
- None
> New block explorer link

- README.md
With pairs NEO-BTC and GAS-BTC
> Added KuCoin

- README.md
> Update with a simple type correction

- README.md
Added 
> * NEO Blockchain Quick Start Guide for .NET Developers - Complete (very detailed) step-by-step guidance with screen shots
to Developer Documentation section with a link to:
[https://github.com/mwherman2000/neo-windocs/blob/master/windocs/quickstart-csharp/README.md](https://github.com/mwherman2000/neo-windocs/blob/master/windocs/quickstart-csharp/README.md)
Best regards, Michael Herman (Toronto)
> Added NEO Blockchain Quick Start Guide for .NET Developers to Dev Doc

- README.md
- resources/python-examples.md
A compiled list of Python s…mart contracts and middleware code examples. Added link to new file in code examples section of readme.
> Added file resources/python-examples.md

- README.md
Added [NEO Blockchain Architecture Reference Model for .NET Developers](https://github.com/mwherman2000/neo-windocs/blob/master/windocs/neo-charm/README.md) to **Developer Documentation**.
The purpose of this document is to document a (software) architecture reference model for the NEO Blockchain platform to enable .NET developers to become more knowledge about the NEO platform more quickly and more easily
> Added NEO Blockchain Architecture Reference Model for .NET Developers

- README.md
- resources/coz_application_form.md
It may be a bit early but I'm propose removal of StackExchange links and references until this is back on the table again.
> Removal of StackExchange references

- README.md
Added section for "Published Articles" to provide links to Medium articles written about NEO.
> Update README.md to add Published Articles

- README.md
Added neo-go repository to the list of SDK's
> Added neo-go to the list of SDK's

- README.md
To prevent others from hitting this iceberg: https://github.com/CityOfZion/neo-python/issues/251
> Added that the bootstrap files are for the C# client

- README.md
Creating a NEO Blockchain Hosted Private Network on Microsoft Azure in Under 30 Minutes
> Added reference to article

- README.md
- resources/neo-competitions.md
> Add NEO dApps Competitions Links

- README.md
Removed outdated and broken links, added a link to a NEO ICO tracker that's up to date
> Updated ICO section

- resources/neo-competitions.md
Added the winners and honorable mentions from the second CoZ competition
> Added dApp Competition #2

- resources/python-examples.md
Added the NEP5 and crowdsale contract demos
> Added additional Python smart contract examples

- README.md
- resources/neo-competitions.md
Fixed the broken link in the main menu and added the winners/runners up for competition 3.
> Competition 3

- README.md
- resources/python-examples.md
Removed a link to a missing section, fixed some ambiguous wording and added some additional wallets to the list.
> Misc cleanup

- README.md
- resources/python-examples.md
I thought it was confusing to have "Code Examples", "Developer Documentation" and "Smart Contract Development". It wasn't clear where to go when scrolling down the page. Not sure how well this solves the issue, would be open to feedback.
> Restructured developer resources

- README.md
Added O3's neo-utils and Ryu Games' neovm-utils SDKs
> Added a few SDKs
